---

  - name: 13.1 Ensure Password Fields are Not Empty (Scored)
    command: awk -F':' '($2 == "" ) { print $1 }' /etc/shadow
    register: awk_empty_shadow
    changed_when: False
    failed_when: awk_empty_shadow.stdout != '' and not lock_shadow_accounts
    tags:
      - section13
      - section13.1

  - name: 13.1 Ensure Password Fields are Not Empty (locking accounts) (Scored)
    command: passwd -l '{{ item }}'
    with_items:
        awk_empty_shadow.stdout_lines
    when: lock_shadow_accounts
    tags:
      - section13
      - section13.1
      
  - name: 13.7.1 Check Permissions on User Home Directories (gather users) (Scored)
    shell: /bin/egrep -v '(root|halt|sync|shutdown|false)' /etc/passwd | /usr/bin/awk -F':' '($7 != "/usr/sbin/nologin") { print $6 }'
    register: home_users
    changed_when: False
    failed_when: False
    tags:
      - section13
      - section13.7

  - name: 13.9 Check Permissions on User .netrc Files (Scored)
    file: >
        path='{{ item }}/.netrc'
        mode='g-rwx,o-rwx'
        recurse=yes
        state=directory
    with_items:
        home_users.stdout_lines
    tags:
      - section13
      - section13.9

  - name: 13.16 Check for Duplicate User Names (Scored)
    shell: cut -f1 -d':' /etc/passwd | sort | uniq -d
    register: uids_list
    failed_when: uids_list.stdout != ''
    changed_when: False
    always_run: True
    tags:
      - section13
      - section13.16

  - name: 13.18 Check for Presence of User .netrc Files (stat) (Scored)
    stat: path='{{ item }}/.netrc'
    with_items: home_users.stdout_lines
    register: netrc_files
    tags:
      - section13
      - section13.18
