---

  - name: 9.2.1 Set Password Creation Requirement Parameters Using pam_cracklib (install) (Scored)
    apt: name=libpam-cracklib state=present
    when: use_pam_cracklib == True
    tags:
      - section9
      - section9.2
      - section9.2.1

  - name: 9.2.1 Set Password Creation Requirement Parameters Using pam_cracklib (Scored)
    lineinfile: >
        dest='/etc/pam.d/common-password'
        regexp="pam_cracklib.so"
        line="password required pam_cracklib.so retry=3 minlen=8 dcredit=-1 lcredit=-1" 
        state=present
    when: use_pam_cracklib == True
    tags:
      - section9
      - section9.2
      - section9.2.1

#Note for section 9.2.2:
#If a user has been locked out because they have reached the maximum consecutive failure count
#defined by denied= in the pam_tally2.so module, the user can be unlocked by issuing the command
#/sbin/pam_tally2 -u username --reset
#This command sets the failed count to 0, effectively unlocking the user
  - name: 9.2.2 Set Lockout for Failed Password Attempts (Not Scored)
    lineinfile: >
        dest='/etc/pam.d/login'
        regexp='pam_tally2'
        line="auth required pam_tally2.so onerr=fail audit silent deny=5 unlock_time=900"
        state=present
    tags:
      - section9
      - section9.2
      - section9.2.2

  - name: 9.2.3 Limit Password Reuse (Scored)
    lineinfile: >
        dest='/etc/pam.d/common-password'
        regexp='remember=5'
        line="password sufficient pam_unix.so remember=5"
        state=present
    tags:
      - section9
      - section9.2
      - section9.2.3

  - name: 9.3 Check if ssh is installed (check) (Not Scored)
    stat: path='/etc/ssh/sshd_config'
    register: ssh_config_file
    tags:
      - section9
      - section9.3
      - section9.3.1

  - include: section_09_level1_03.yml
    when: ssh_config_file.stat.exists == True