---

  - name: 2.5 Create Separate Partition for /var (Scored)
    command: grep '\s/var\s' /etc/fstab
    register: var_partition
    failed_when: var_partition.rc == 1
    changed_when: False
    ignore_errors: True
    tags:
      - section2
      - section2.5

  - name: 2.6 Bind Mount the /var/tmp directory to /tmp (Scored)
    mount: name="/var/tmp" src="/tmp" opts=bind state=mounted fstype=ext4
    when: partitioning == True
    tags:
      - section2
      - section2.6

  - name: 2.7 Create Separate Partition for /var/log (Scored)
    command: grep '\s/var\/log\s' /etc/fstab
    register: var_log_partition
    failed_when: var_log_partition.rc == 1
    changed_when: False
    ignore_errors: True
    tags:
      - section2
      - section2.7

  - name: 2.8 Create Separate Partition for /var/log/audit (Scored)
    command: grep '\s/var\/log\/audit\s' /etc/fstab
    register: var_log_audit_partition
    failed_when: var_log_audit_partition.rc == 1
    changed_when: False
    ignore_errors: True
    tags:
      - section2
      - section2.8

  - name: 2.9 Create Separate Partition for /home (Scored)
    command: grep '\s/home\s' /etc/fstab
    register: home_partition
    failed_when: home_partition.rc == 1
    changed_when: False
    ignore_errors: True
    tags:
      - section2
      - section2.9