# Please enter following parameters before system hardening

# Section hugin
use_apt_cacher: False

# Section 02

partitioning: False

# True if run/shm is write-protected.
run_shm_read_only: False

# Section 07

# Set this flag if the kernel has TCP syncookies support.
enable_tcp_syncookies: True

# Enable the activate_ufw variable with True to install and enable service on boot.
# NOTE: If not properly configured it may result in incorrect services behavior.
activate_ufw: True

# Disable all ipv6 interfaces. Suggested if the protocol is not used.
disable_ipv6: True


# Section 08

# Set auditd logs file size in /var/log/auditd
max_log_file_auditd: 200

# Set this flag if you have a remote rsyslog server to send logs.
# WARNING: Update the IP address or rsyslog will hit 100% of the CPU usage.
set_rsyslog_remote: False

# Set rsyslog's logs remote server address to send logs. 
# WARNING: Update the IP address without localhost address or rsyslog will hit 100% of the CPU usage
remote_logs_host_address: X.X.X.X

# Section 09

# This variable will install and setup the pam_cracklib module, enforcing strong passwords settings.
use_pam_cracklib: True

# Section 13

# This variable defines if accounts without password have to be locked
lock_shadow_accounts: False

# The modification of user homes may lock users and set the system in an errored state. Set to false if one of the user is using / as home.
modify_user_homes: True
