---
galaxy_info:
  author: Vedat Nommaz
  description: OSSEC with JSON support and gmail alerting
  company: Hugin Retail Solutions
  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license GPLv2
  min_ansible_version: 1.7
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Ubuntu
    versions:
    - saucy
    - trusty
    - utopic
  categories:
  - monitoring
dependencies: []
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
  
