---

#########################
# CIS Hardening         #
#########################

- hosts: master
  sudo: true
  tags: cis
  roles:
    - ansible-cis

#########################
# CIS Hardening         #
#########################

- hosts: master
  sudo: true
  tags: ossec
  roles:
    - ansible-ossec
    
#########################
# FTP                   #
#########################

- hosts: master
  sudo: true
  tags: vsftpd
  roles:
    - ansible-vsftpd
    
    
# HTTP server           #
#########################

- hosts: master
  sudo: true
  tags: nginx
  roles:
     - ansible-nginx