---

#########################
# CIS Hardening         #
#########################

- hosts: master
  sudo: true
  tags: cis
  roles:
    - ansible-cis
    
#########################
# FTP                   #
#########################

- hosts: master
  sudo: true
  tags: vsftpd
  roles:
    - ansible-vsftpd
    
#########################
# HTTP server           #
#########################

- hosts: master
  sudo: true
  tags: nginx
  
  tasks:
    - name: create root directory
      file: path={{ nginx_root}} state=directory owner=www-data group=www-data
  roles:
     - ansible-nginx
    
#########################
# OSSEC Client          #
#########################

- hosts: master
  sudo: true
  tags: ossec
  vars: 
    ossec_server_ip: 192.168.88.10
  roles:
    - ansible-ossec-agent