---
# ansible-playbook -i ../../common/XXX/hosts repo.yml -u YYY -v 
# XXX: dev,test,prod
# YYY: remote user login name

#########################
# CIS Hardening         #
#########################

- hosts: reposervers
  sudo: true
  tags: cis
  roles:
#    - ansible-cis
    
#########################
# FTP                   #
#########################

- hosts: reposervers
  sudo: true
  tags: vsftpd
  roles:
    - ansible-vsftpd
    
#########################
# HTTP server           #
#########################

- hosts: reposervers
  sudo: true
  tags: nginx
  tasks:
    - name: create root directory
      file: path={{ nginx_root}} state=directory owner=www-data group=www-data
  roles:
#     - ansible-nginx
    
#########################
# OSSEC Client          #
#########################

- hosts: reposervers
  sudo: true
  tags: ossec
  roles:
    - ansible-ossec-agent