---

# ansible-playbook -i ../../vagrant-ansible-common/XXX/hosts repo.yml -v

#########################
# CIS Hardening         #
#########################

- hosts: paris-repo
  sudo: true
  tags: cis
  roles:
    - role: ansible-cis
    
#########################
# FTP Server            #
#########################

- hosts: paris-repo
  sudo: true
  tags: vsftpd
  roles:
    - ansible-vsftpd

#########################
# HTTP server           #
#########################

- hosts: paris-repo
  sudo: true
  tags: nginx
  roles:
     - ansible-nginx