---

# ansible-playbook -i ../../vagrant-ansible-common/XXX/hosts repo.yml -v

#########################
# CIS Hardening         #
#########################

- hosts: reposervers
  sudo: true
  tags: cis
  roles:
    - ansible-cis
    
#########################
# FTP                   #
#########################

- hosts: reposervers
  sudo: true
  tags: vsftpd
  roles:
    - ansible-vsftpd
    
    
# HTTP server           #
#########################

- hosts: reposervers
  sudo: true
  tags: nginx
  roles:
     - ansible-nginx
    
#########################
# OSSEC Client          #
#########################

- hosts: reposervers
  sudo: true
  tags: ossec
  roles:
    - ansible-ossec-agent