---
# The user to run nginx
nginx_user: "www-data"

nginx_hhvm: |
      add_header X-backend hhvm;
      try_files $uri $uri/ /index.php?$args;
      location ~ \.(hh|php)$ {
        try_files     $uri =404;
        fastcgi_pass  unix:/var/run/hhvm/sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include       fastcgi_params;
      }

# A list of directives for the events section.
nginx_events_params:
  - worker_connections 512

# A list of hashs that define the servers for nginx,
# as with http parameters. Any valid server parameters
# can be defined here.
nginx_http_params:
  - sendfile on
  - access_log /var/log/nginx/access.log

nginx_sites:
 default:
     - listen 4443 #TODO var this value
     - server_name repo
     - root /var/www/nginx-default/packageserver
     - index index.html
     - ssl on
     - ssl_certificate {{ openssl_certs_path }}/{{ vsftpd_cert_file }}
     - ssl_certificate_key {{ openssl_keys_path }}/{{ vsftpd_key_file }}

     - ssl_session_timeout 5m
     - ssl_protocols TLSv1.2
     - ssl_ciphers "HIGH:!aNULL:!MD5 or HIGH:!aNULL:!MD5:!3DES"
     - ssl_prefer_server_ciphers on
     - location / { try_files $uri $uri/ =404; }
 hhvm_test:
     - |
       listen 80;
       server_name test_hhvm;
       root "/tmp/hhvm";
       {{nginx_hhvm}}

# A list of hashs that define additional configuration
nginx_configs:
  proxy:
      - proxy_set_header X-Real-IP  $remote_addr
      - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
  upstream:
      - upstream foo { server 127.0.0.1:8080 weight=10; }
  geo:
      - geo $local {
          default 0;
          127.0.0.1 1;
        }
  gzip:
      - gzip on
      - gzip_disable msie6

# A list of hashs that define uer/password files
nginx_auth_basic_files:
   demo:
     - foo:$apr1$mEJqnFmy$zioG2q1iDWvRxbHuNepIh0 # foo:demo , generated by : htpasswd -nb foo demo
     - bar:$apr1$H2GihkSo$PwBeV8cVWFFQlnAJtvVCQ. # bar:demo , generated by : htpasswd -nb bar demo
