---
# The user to run nginx
nginx_user: "www-data"
nginx_root: "/var/www/nginx-default/packageserver"

# A list of directives for the events section.
nginx_events_params:
  - worker_connections 512

# A list of hashs that define the servers for nginx,
# as with http parameters. Any valid server parameters
# can be defined here.
nginx_http_params:
  - sendfile on
  - access_log /var/log/nginx/access.log

nginx_sites:
 default:
     - listen 4443 #TODO var this value
     - server_name repo
     - root {{ nginx_root }}
     - index index.html
     - ssl on
     - ssl_certificate {{ openssl_certs_path }}/{{ vsftpd_cert_file }}
     - ssl_certificate_key {{ openssl_keys_path }}/{{ vsftpd_key_file }}

     - ssl_session_timeout 5m
     - ssl_protocols TLSv1.2
     - ssl_ciphers "HIGH:!aNULL:!MD5 or HIGH:!aNULL:!MD5:!3DES"
     - ssl_prefer_server_ciphers on
     - location / { try_files $uri $uri/ =404; }